version: '3.1'

services:
  postgres:
    build: .
    container_name: estoque-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: produto
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

volumes:
  postgres_data:
